/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as GrantsIndexRouteImport } from './routes/grants.index'
import { Route as LawsIndexRouteImport } from './routes/laws.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsIndexRoute = GrantsIndexRouteImport.update({
  id: '/grants/',
  path: '/grants/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsIndexRoute = LawsIndexRouteImport.update({
  id: '/laws/',
  path: '/laws/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/signin': typeof SigninRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/grants/': typeof GrantsIndexRoute
  '/laws/': typeof LawsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/signin': typeof SigninRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/grants': typeof GrantsIndexRoute
  '/laws': typeof LawsIndexRoute
  '/news': typeof NewsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/signin': typeof SigninRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/grants/': typeof GrantsIndexRoute
  '/laws/': typeof LawsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/signin'
    | '/services/$slug'
    | '/blogs/'
    | '/grants/'
    | '/laws/'
    | '/news/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/signin'
    | '/services/$slug'
    | '/blogs'
    | '/grants'
    | '/laws'
    | '/news'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/signin'
    | '/services/$slug'
    | '/blogs/'
    | '/grants/'
    | '/laws/'
    | '/news/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  ContactRoute: typeof ContactRoute
  SigninRoute: typeof SigninRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  GrantsIndexRoute: typeof GrantsIndexRoute
  LawsIndexRoute: typeof LawsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants/': {
      id: '/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof GrantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws/': {
      id: '/laws/'
      path: '/laws'
      fullPath: '/laws/'
      preLoaderRoute: typeof LawsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  ContactRoute: ContactRoute,
  SigninRoute: SigninRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  GrantsIndexRoute: GrantsIndexRoute,
  LawsIndexRoute: LawsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
